server:
  port: 4004

spring:
  application:
    name: api-gateway


## Gateway config without eureka service ##
#  cloud:
#    gateway:
#      routes:
#        - id: patient-service-route
#          uri: http://patient-service:4000
#          predicates:
#            - Path=/api/patient/**
#          filters:
#            - StripPrefix=1
#
#        - id: api-docs-patient-route
#          uri: http://patient-service:4000
#          predicates:
#            - Path=/api-docs/patient
#          filters:
#            - RewritePath=/api-docs/patient,/v3/api-docs

#  redis:
#    host: redis
#    port: 6379
  cloud:
    gateway:
#      default-filters:
#        - name: RequestRateLimiter
#          args:
#            redis-rate-limiter.replenishRate: 5
#            redis-rate-limiter.burstCapacity: 10
#            key-resolver: "#{@ipKeyResolver}"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

        # Route for auth service
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
              - Path=/auth/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: authServiceCircuitBreaker
                fallbackUri: forward:/fallback/auth

        # Route for patient service
        - id: patient-service-route
          uri: lb://patient-service
          predicates:
            - Path=/admin/patient/**, /admin/patient
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: patientServiceCircuitBreaker
                fallbackUri: forward:/fallback/patient

        # Route for doctor service
        - id: doctor-service-route
          uri: lb://doctor-service
          predicates:
            - Path=/admin/doctor/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: doctorServiceCircuitBreaker
                fallbackUri: forward:/fallback/doctor

        # Route for appointment service
        - id: appointment-service-route
          uri: lb://appointment-service
          predicates:
            - Path=/admin/appointment/**, /admin/appointment
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: appointmentServiceCircuitBreaker
                fallbackUri: forward:/fallback/appointment

        # Route for billing service
        - id: billing-service-route
          uri: lb://billing-service
          predicates:
            - Path=/admin/billing/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: billingServiceCircuitBreaker
                fallbackUri: forward:/fallback/billing

        # Route for openapi doc page for patient service
        - id: api-docs-patient-route
          uri: lb://patient-service
          predicates:
            - Path=/api-docs/patient
          filters:
            - RewritePath=/api-docs/patient,/v3/api-docs

        # Route for openapi doc page for doctor service
        - id: api-docs-doctor-route
          uri: lb://doctor-service
          predicates:
            - Path=/api-docs/doctor
          filters:
            - RewritePath=/api-docs/doctor,/v3/api-docs

        # Route for openapi doc page for auth service
        - id: api-docs-auth-route
          uri: lb://auth-service
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.netflix.discovery: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always
  health.circuitBreakers.enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
    instances:
      patientServiceCircuitBreaker:
        baseConfig: default
      doctorServiceCircuitBreaker:
        baseConfig: default
      appointmentServiceCircuitBreaker:
        baseConfig: default
      analyticsServiceCircuitBreaker:
        baseConfig: default
      authServiceCircuitBreaker:
        baseConfig: default
      billingServiceCircuitBreaker:
        baseConfig: default


