# import the local config file to load data for database connection
spring:
  config:
    import: classpath:localEnv.yaml
  application:
    name: patient-service

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

# Hibernate configuration
# Included in the docker environment
# UNCOMMENT TO APPLY WHEN RUN APPLICATION OUTSIDE OF DOCKER
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#
#  sql:
#    init:
#      mode: ALWAYS

# The port number with current service
server:
  port: 4000

# display all logs in the Terminal
logging:
  level:
    root: info
    org:
      springframework:
        aop: DEBUG
        context:
          annotation:
            AnnotationConfigApplicationContext: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
