server:
  port: 8761

spring:
  application:
    name: eureka-server

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:1008/eureka

  dashboard:
    enabled: true
    path: /dashboard
