spring:
  application:
    name: analytics-service

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer


server:
  port: 4003

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka