spring:
  application:
    name: appointment-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.mhp.appointment_service.model"
        spring.json.value.default.type: com.mhp.appointment_service.model.Appointment
        spring.json.use.type.headers: false

# The port number with current service
server:
  port: 4006

# display all logs in the Terminal
logging:
  level:
    root: info
    org:
      springframework:
        aop: DEBUG
        context:
          annotation:
            AnnotationConfigApplicationContext: DEBUG


resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
    instances:
      patient-service:
        baseConfig: default
      doctor-service:
        baseConfig: default

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka